apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - admin-service.yaml
  - poststart-configmap.yaml
  - ingress-class.yaml
  - ingress.yaml
  - kong-ingress-controller.yaml
