apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: secretstore-validate
webhooks:
  - name: "validate.secretstore.external-secrets.io"
    clientConfig:
      service:
        namespace: external-secrets
  - name: "validate.clustersecretstore.external-secrets.io"
    clientConfig:
      service:
        namespace: external-secrets
