apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: externalsecret-validate
webhooks:
  - name: "validate.externalsecret.external-secrets.io"
    clientConfig:
      service:
        namespace: external-secrets
