apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: kind-bpl-dev
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    tags:
      - env:dev
      - service:reliable-message-api
      - project:reliable-message-api
      - managed-by:datadog-operator
    kubelet:
      host:
        fieldRef:
          fieldPath: spec.nodeName
      tlsVerify: false
  features:
    admissionController:
      enabled: true
      mutateUnlabelled: true
    asm:
      threats:
        enabled: true
      sca:
        enabled: true
      iast:
        enabled: true
    apm:
      enabled: true
      instrumentation:
        enabled: true
        targets:
          - name: default-target
            ddTraceVersions:
              java: "1"
              python: "4"
              js: "5"
              php: "1"
              dotnet: "3"
              ruby: "2"
            ddTraceConfigs:
              - name: DD_PROFILING_ENABLED
                value: auto
              - name: DD_DATA_STREAMS_ENABLED
                value: "true"
      hostPortConfig:
        enabled: true
        hostPort: 8126
    clusterChecks:
      enabled: true
    cspm:
      enabled: true
    cws:
      enabled: true
    dogstatsd:
      nonLocalTraffic: true
      hostPortConfig:
        enabled: true
        hostPort: 8125
      originDetectionEnabled: true
    ebpfCheck:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    kubeStateMetricsCore:
      enabled: true
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
      containerCollectUsingFiles: true
      autoMultiLineDetection: true
    npm:
      enabled: true
    oomKill:
      enabled: true
    orchestratorExplorer:
      enabled: true
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: otel-grpc
        - containerPort: 4318
          hostPort: 4318
          name: otel-http
    processDiscovery:
      enabled: true
    prometheusScrape:
      enabled: true
    remoteConfiguration:
      enabled: true
    sbom:
      enabled: true
      containerImage:
        enabled: true
      host:
        enabled: true
    serviceDiscovery:
      enabled: true
      networkStats:
        enabled: true
    tcpQueueLength:
      enabled: true
    usm:
      enabled: true
  override:
    clusterAgent:
      replicas: 1
      containers:
        cluster-agent:
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
    nodeAgent:
      env:
        - name: DD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      containers:
        agent:
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1Gi"
        process-agent:
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
        trace-agent:
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
        security-agent:
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
